filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
#    multiline.type: pattern
#    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
#    multiline.negate: true
#    multiline.match: after
#    multiline.max_lines: 10
#    multiline.timeout: 5s
    include_lines:
      - '^[0-9]{4}-[0-9]{2}-[0-9]{2}'

processors:
  - add_docker_metadata: {}
  - drop_event:
      when:
        not:
          or:
            - equals:
                container.name: "user-service-cvconnect"
            - equals:
                container.name: "core-service-cvconnect"
            - equals:
                container.name: "notify-service-cvconnect"

output.logstash:
  hosts: ["logstash:5044"]
